# Site settings
title: AKADALYMENTESITO
email: akadalymentes1@opesun.eu
description: > # this means to ignore newlines until "baseurl:"
 Az AKADALYMENTESITO weboldalakat alakit at vizualisan korlatozott felhasznalok szamara. Az AKADALYMENTESITO fejlesztes alatt all.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laller.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  laller

# Build settings
markdown: kramdown
