# Site settings
title: AKADALYMENTESITO
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Az oldal mas oldalakat jelenit meg, akadalymentesitve. Kivancsi ra, hogy az On oldalanak hogyan kellene kinezni?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  laller

# Build settings
markdown: kramdown
